import Head from "next/head";
import Blog from "@/types/blog";
import Spotlight from "@/components/spotlight/Spotlight";
import News from "@/components/news/News";

export default function Home() {
  return (
    <>
      <Head>
        <title>Blog In Progress</title>
        <meta name="description" content="Generated by Aresha" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        {Blog.map((item) => (
          <div>
            <Spotlight item={item} />
            {item.news.map((news) => (
              <News news={news} />
            ))}
          </div>
        ))}
      </main>
    </>
  );
}
