import Head from "next/head";
import Blog from "@/types/blog";
import Spotlight from "@/components/spotlight/Spotlight";
import News from "@/components/news/News";

export default function Home() {
  return (
    <>
      <Head>
        <title>Blog In Progress</title>
        <meta name="description" content="Generated by Aresha" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main style={{ padding: "40px" }}>
        {Blog.map((item) => (
          <div style={{ display: "flex", gap: "20px", marginBottom: "100px" }}>
            <Spotlight item={item} />
            <div
              style={{
                width: "50%",
                display: "grid",
                gridTemplateColumns: "repeat(2,1fr)",
                gridAutoRows: "auto",
                gridGap: "10px",
              }}
            >
              {item.news.map((news) => (
                <News news={news} />
              ))}
            </div>
          </div>
        ))}
      </main>
    </>
  );
}
