import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Blog In Progress</title>
        <meta name="description" content="Generated by Aresha" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1>Marikuna</h1>
      </main>
    </>
  );
}
